<a href="https://colab.research.google.com/github/mirpouya/Pytorch_Tutorial/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import torch
print(torch.__version__)

2.0.1+cu118


<b> Introduction to Tensors <b>

In [28]:
# scalar
 
s = torch.tensor(7)
s

tensor(7)

In [29]:
# tensor dimension

s.ndim

0

In [30]:
# get tensor back as python int

s.item()

7

<b> Vectors </b>

In [31]:
v = torch.tensor([7, 1])
v

tensor([7, 1])

In [32]:
v.ndim

1

In [33]:
v.shape

torch.Size([2])

<b> Matrix </b>

In [34]:
m = torch.tensor([[7, 1],
                  [8, 2]])

m

tensor([[7, 1],
        [8, 2]])

In [35]:
m.ndim

2

In [36]:
m.shape

torch.Size([2, 2])

In [37]:
m[0]

tensor([7, 1])

In [38]:
m[1]

tensor([8, 2])

In [39]:
m[0][1]

tensor(1)

In [40]:
m[1][1]

tensor(2)

In [41]:
 # 3-d tensors

m_3d = torch.tensor([[[1,2,3,4],[0, 0, 0, 0]]
                       ])
m_3d

tensor([[[1, 2, 3, 4],
         [0, 0, 0, 0]]])

In [42]:
m_3d.shape

torch.Size([1, 2, 4])

In [43]:
m_3d = torch.tensor([[[1,2,3,4],[0, 0, 0, 0]],
                     [[1,2,3,4],[0, 0, 0, 0]]
                       ])
m_3d

tensor([[[1, 2, 3, 4],
         [0, 0, 0, 0]],

        [[1, 2, 3, 4],
         [0, 0, 0, 0]]])

In [44]:
m_3d.shape

torch.Size([2, 2, 4])

<b> Random Tensors </b>

In [45]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3105, 0.3718, 0.9020, 0.5270],
        [0.9041, 0.3426, 0.1126, 0.6597],
        [0.1527, 0.6084, 0.4677, 0.4730]])

In [46]:
# number of dimensions 
random_tensor.ndim

2